spring:
  redis:
    host: localhost
    port: 6379
  cache:
    type: redis
    redis:
      time-to-live: PT30S
      key-prefix: "10010287:"
      custom:
        ttl:
          "echo": PT5M
          "student": PT1H
  datasource:
    url: jdbc:h2:mem:elijah
    username: foo
    password: bar
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  h2:
    console:
      enabled: true
  application:
    custom:
      idc-code: 1